### ISSUE TITLE
Factory always creates new instance…

### ISSUE THREAD

**Issue by heiglandreas** [schlessera/as-speaking#1]
Due to [resetting instance variable](https://github.com/schlessera/as-speaking/blob/8f870de1b17ebed9aeaeb96f5a0d69eacb695d46/src/PluginFactory.php#L34) on calling ```create()``` the following ```if```-condition is somehow senseles, isn't it?

I'd either remove the ```if```  or add a static class-variable that is checked and not always reset. :wink:

**Comment by johnbillion** [comment]
This syntax simply sets the initial state of the static variable. Once it's been initialised once, its value is retained between calls to the method.

**Comment by heiglandreas** [comment]
Thanks for pointing out the static! I'm not used to using ```static``` within a class-method as there are different solutions to that. For example defining the variable as private class-variable like this:

```php
class PluginFactory() {
    private static $class = null;
    public static function create() {
        if (null === self::$class) {
            self::$class = new Plugin();
        }
        return self::$class;
    }
```

That'd separate initialising the variable from the actual function. And that'd also allow setting the variable for testing purposes.

But you're right that it works as well as it is…

**Comment by schlessera** [comment]
@heiglandreas I generally use properties for state that does actually make conceptual sense for the object.

Here in this case, the state I want to store is just an irrelevant implementation detail of the instantiation function, that's why I keep it within the scope of that function.

This is all just about personal preference in the end, I guess.
