### ISSUE TITLE
Question about closures on hooks

### ISSUE THREAD

**Issue by JPry** [schlessera/as-speaking#3]
In many places throughout the codebase, you opt to attach a closure to a given hook rather than an instance and method. For example, here's a snippet from `src/Metabox/BaseMetabox.php`:

```php
	/**
	 * Register the persistence hooks to be triggered by a save attempt.
	 *
	 * @since 0.1.0
	 */
	protected function register_persistence_hooks() {
		$closure = $this->get_persistence_closure();
		add_action( 'save_post', $closure );
	}

	/**
	 * Return the persistence closure.
	 *
	 * @since 0.1.0
	 *
	 * @return Closure
	 */
	protected function get_persistence_closure() {
		return function ( $post_id ) {
			// Verify nonce and bail early if it doesn't verify.
			if ( ! $this->verify_nonce() ) {
				return $post_id;
			}

			// Bail early if this is an autosave.
			if ( wp_is_post_autosave( $post_id ) ) {
				return $post_id;
			}

			// Bail early if this is a revision.
			if ( wp_is_post_revision( $post_id ) ) {
				return $post_id;
			}

			// Check the user's permissions.
			if ( ! current_user_can( 'edit_post', $post_id ) ) {
				return $post_id;
			}

			// Check if there was a multisite switch before.
			if ( is_multisite() && ms_is_switched() ) {
				return $post_id;
			}

			$this->persist( $post_id );

			return $post_id;
		};
	}
```

What is the benefit to adding a closure to the `save_post` hook rather than hooking public class method directly?

**Comment by schlessera** [comment]
Hey Jeremy,

In the particular case above, there's not really any benefit to be had. I probably had something in mind, but finally implemented something else, and the closure was still in place.

However, in some of the other places where I'm using closures, it is because closures are more flexible for later extending the code. I have added a system with deferred actions, and the main difference between closures and between adding methods directly is that closures are just a general variable that you can pass around however you want. This way, you can either execute the closure, or forward it to some other code.

See here for why the closures are useful: https://github.com/schlessera/as-speaking/blob/8f870de1b17ebed9aeaeb96f5a0d69eacb695d46/src/Assets/BaseAsset.php#L106-L118

**Comment by JPry** [comment]
That makes sense. Thanks for the explanation!
